name               = "tidel-api"
main               = "src/index.ts"
compatibility_date = "2026-03-20"
workers_dev        = true
preview_urls       = true

[placement]
mode = "smart"

[triggers]
crons = ["0 6 * * *", "0 15 * * *"]

[observability.logs]
enabled = true
invocation_logs = true

[[unsafe.bindings]]
name         = "RATE_LIMITER"
type         = "ratelimit"
namespace_id = "1001"
simple       = { limit = 60, period = 60 }

[env.production]
name = "tidel-api"
vars = { CLOUDFLARE_ZONE_ID = "9a23d22a10f0ec01f5771ddc5de8aaac" }

[[env.production.routes]]
pattern = "api.tidel.app"
custom_domain = true

[env.production.triggers]
crons = ["0 6 * * *", "0 15 * * *"]

[[env.production.unsafe.bindings]]
name         = "RATE_LIMITER"
type         = "ratelimit"
namespace_id = "1001"
simple       = { limit = 60, period = 60 }

